-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MEAL_RECORDED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MEAL_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MEAL_DELETED';
