-- AlterTable
ALTER TABLE "meal_entries" ALTER COLUMN "lunch" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "lunch" SET DEFAULT 0,
ALTER COLUMN "dinner" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "dinner" SET DEFAULT 0;

-- AlterTable
ALTER TABLE "meal_plans" ALTER COLUMN "lunch" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "lunch" SET DEFAULT 0,
ALTER COLUMN "dinner" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "dinner" SET DEFAULT 0;

-- AlterTable
ALTER TABLE "member_bills" ALTER COLUMN "mealCount" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "billing_cycles" ALTER COLUMN "totalMeals" SET DATA TYPE DOUBLE PRECISION;
