-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DEPOSIT_ADDED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DEPOSIT_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EXPENSE_ADDED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EXPENSE_UPDATED';

-- AlterTable
ALTER TABLE "mess_members" ADD COLUMN "defaultLunch" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "defaultDinner" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "feedSeenAt" TIMESTAMP(3);
