import PDFDocument from "pdfkit";

export type InvoiceLine = {
	label: string;
	amount: string;
	strong?: boolean;
};

export type InvoiceInput = {
	title: string;
	invoiceNumber: string;
	issuedOn: string;
	messName: string;
	memberName: string;
	period: string;
	lines: InvoiceLine[];
	totalLabel: string;
	totalAmount: string;
	note?: string;
};

const INK = "#123c4a";
const MUTED = "#71808a";
const BRAND = "#087f8c";
const RULE = "#dfe7ea";

export const buildInvoicePdf = (input: InvoiceInput): Promise<Buffer> => {
	const doc = new PDFDocument({ size: "A4", margin: 56 });

	const chunks: Buffer[] = [];

	doc.on("data", (chunk: Buffer) => chunks.push(chunk));

	const finished = new Promise<Buffer>((resolve, reject) => {
		doc.on("end", () => resolve(Buffer.concat(chunks)));
		doc.on("error", reject);
	});

	const left = doc.page.margins.left;
	const right = doc.page.width - doc.page.margins.right;

	doc
		.fillColor(BRAND)
		.font("Helvetica-Bold")
		.fontSize(22)
		.text("MessMate", left, 56);

	doc
		.fillColor(MUTED)
		.font("Helvetica")
		.fontSize(10)
		.text("Smart Mess & Shared Housing Management", { continued: false });

	doc
		.fillColor(INK)
		.font("Helvetica-Bold")
		.fontSize(16)
		.text(input.title, left, 112, { width: right - left, align: "right" });

	doc
		.fillColor(MUTED)
		.font("Helvetica")
		.fontSize(9)
		.text(`No. ${input.invoiceNumber}`, { width: right - left, align: "right" })
		.text(`Issued ${input.issuedOn}`, { width: right - left, align: "right" });

	doc.moveTo(left, 156).lineTo(right, 156).strokeColor(RULE).stroke();

	doc
		.fillColor(MUTED)
		.font("Helvetica")
		.fontSize(9)
		.text("MESS", left, 174)
		.fillColor(INK)
		.font("Helvetica-Bold")
		.fontSize(12)
		.text(input.messName, left, 188);

	doc
		.fillColor(MUTED)
		.font("Helvetica")
		.fontSize(9)
		.text("MEMBER", left + 250, 174)
		.fillColor(INK)
		.font("Helvetica-Bold")
		.fontSize(12)
		.text(input.memberName, left + 250, 188);

	doc
		.fillColor(MUTED)
		.font("Helvetica")
		.fontSize(9)
		.text("PERIOD", left, 224)
		.fillColor(INK)
		.font("Helvetica-Bold")
		.fontSize(12)
		.text(input.period, left, 238);

	let y = 286;

	doc
		.fillColor(MUTED)
		.font("Helvetica")
		.fontSize(9)
		.text("DESCRIPTION", left, y)
		.text("AMOUNT (BDT)", left, y, { width: right - left, align: "right" });

	y += 18;
	doc.moveTo(left, y).lineTo(right, y).strokeColor(RULE).stroke();
	y += 12;

	for (const line of input.lines) {
		doc
			.fillColor(line.strong ? INK : MUTED)
			.font(line.strong ? "Helvetica-Bold" : "Helvetica")
			.fontSize(11)
			.text(line.label, left, y)
			.fillColor(INK)
			.font(line.strong ? "Helvetica-Bold" : "Helvetica")
			.text(line.amount, left, y, { width: right - left, align: "right" });

		y += 22;
	}

	y += 4;
	doc.moveTo(left, y).lineTo(right, y).strokeColor(RULE).stroke();
	y += 14;

	doc
		.fillColor(INK)
		.font("Helvetica-Bold")
		.fontSize(13)
		.text(input.totalLabel, left, y)
		.text(`BDT ${input.totalAmount}`, left, y, {
			width: right - left,
			align: "right",
		});

	if (input.note) {
		y += 40;

		doc
			.fillColor(MUTED)
			.font("Helvetica")
			.fontSize(10)
			.text(input.note, left, y, { width: right - left });
	}

	doc
		.fillColor(MUTED)
		.font("Helvetica")
		.fontSize(8)
		.text(
			"Generated by MessMate. This document is a record of the mess ledger for the period shown.",
			left,
			doc.page.height - 80,
			{ width: right - left, align: "center" },
		);

	doc.end();

	return finished;
};
